"""empty message

Revision ID: a73297ad8816
Revises: 
Create Date: 2023-04-23 16:17:45.179382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73297ad8816'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('cid', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('cid')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
